import java.util.*;
class Example{
	public static void main(String args[]){
		Scanner input=new Scanner(System.in);	
	System.out.println("                                ===========================================================================================");
	System.out.println("                                ||                                                                                       ||");
	System.out.println("                                ||                                                                                       ||");
	System.out.println("                                ||                                              =*%@@%*=                                 ||");
	System.out.println("                                ||                                            =@@@@@@@@@@=                               ||");
	System.out.println("                                ||                      .=#@@#+.             =@@@@@@@@@@@@=                              ||");
	System.out.println("                                ||                     :@@@@@@@@-           @@@@@@@@@@@@@@@%                             ||");
	System.out.println("                                ||                     @@@@@@@@@@            =@@@@@@@@@@@@=                              ||");
	System.out.println("                                ||                     :@@@@@@@@-             =@@@@@@@@@@=                               ||");
	System.out.println("                                ||                      .+#@@#+.                =*%@@%*=                                 ||");
	System.out.println("                                ||                     =#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#=                            ||");
	System.out.println("                                ||                    *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*     -+%@#                 ||");
	System.out.println("                                ||                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  :+#@@@@@                 ||");
	System.out.println("                                ||                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                 ||");
	System.out.println("                                ||                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                 ||");
	System.out.println("                                ||                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                 ||");
	System.out.println("                                ||                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                 ||");
	System.out.println("                                ||                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  :+#@@@@@                 ||");
	System.out.println("                                ||                    *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*     -+%@#                 ||");
	System.out.println("                                ||                     =#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#=                            ||");
	System.out.println("                                ||                                    .%@@@++@@@%:                                       ||");
	System.out.println("                                ||                                  .%@@@%.  .%@@@%:                                     ||");
	System.out.println("                                ||                                   =%%=      =%%=                                      ||");
	System.out.println("                                ||                                                                                       ||");
	System.out.println("                                ||                                                                                       ||");
	System.out.println("                                ||                   ___  ____________   __________  __________  _____                   ||");
	System.out.println("                                ||                  / __\\/_    _/   _/  /  __/_  _/\\/   /  __/ \\/   / \\                  ||");
	System.out.println("                                ||                 /    / /  /   \\ \\   /  /__ / //     /  _// /\\/  / __\\                 ||");
	System.out.println("                                ||                /_/\\_\\ /__/ /____/   \\____/___/_/\\__/____/_/  /_/_/  \\\\                ||");
	System.out.println("                                ||                                                                                       ||");
	System.out.println("                                ===========================================================================================");
System.out.println("\n");
	System.out.print("				 Enter Date :");
        String x=input.next();
	System.out.print("			         Location :");
	String y=input.next();
	System.out.println("                                                   _            _ _       _     _        ____ _ _                                    ");
	System.out.println("                                                  /_\\__ _____ _(_) |___ _| |__|  |___   | ___(_) |_ __  ___                                 ");
	System.out.println("                                                 / _ \\ / /  _ || | /   _ | '_ \\ /  _)   | _| | | | '  \\(__<                                 ");
	System.out.println("                                                /_/\\_ \\_/\\__,_||_|_\\__,_ |_,__/_\\__|    |_|  |_|_|_|_|_/__/                               ");
	System.out.println("\n");
	System.out.println("                                              ==============================================================");
System.out.println("\n");
	System.out.println("                                 1) Movie 1 - Hall 1                                                     2) Movie 2 - Hall 2");
	System.out.println("                                 3) Movie 3 - Hall 3                                                     4) Movie 4 - Hall 4");
System.out.println("\n");
	System.out.print("				 Enter Movie Number :");
	int z=input.nextInt();
System.out.println("\n");
System.out.println("\n");
	System.out.println("                                                                _____                                                           ");
	System.out.println("                                                               |_   _|_                                                  ");
	System.out.println("                                                                 | | ( )_ __ ___   __                                                   ");
	System.out.println("                                                                 | | | | '_ ' _ \\/ _ \\                                 ");
	System.out.println("                                                                 | | | | | | | | |  _/                                                  ");
	System.out.println("                                                                 |_| |_|_| |_| |_|\\__|                                        ");
	System.out.println("                                              ==============================================================");
System.out.println("\n");
	System.out.println("                                                                     1) 9.00 A.M                                                  ");
	System.out.println("                                                                     2) 2.00 P.M                                                  ");
	System.out.println("                                                                     3) 7.00 P.M                                                  ");
System.out.println("\n");
	System.out.print("				 Enter Time :");
	String w=input.next();
	System.out.println("                                                         ______           __                                                      ");
	System.out.println("                                                        /  ___ \\         | |                                                   ");
	System.out.println("                                                        | /   \\/_  _  ___| |__ ____ _ __ ___   ___ _ ____                                       ");
	System.out.println("                                                        | |     | |  /  _|  _ / _ \\| '_ ' _ \\/ _  \\ ' __|                                 ");
	System.out.println("                                                        | \\__/\\ |_|  \\__ \\ ||  (_) | | | | | |  __/  |                                ");
	System.out.println("                                                        \\_____/\\__,_|___/ \\__\\____/|_| |_| |_|\\___| _|                                              ");
	System.out.println("                                                 ==============================================================");
System.out.println("\n");
	System.out.print("				 Name :");
        String u=input.next();
System.out.println("\n");
	System.out.print("				 Phone Number :");
	int q=input.nextInt();
System.out.println("\n");
	System.out.print("				 Child OR Parent :");
        String i=input.next();
System.out.println("\n");
	System.out.print("				 Number of Tickets :");
	int r=input.nextInt();
System.out.println("\n");
	System.out.println("                                ========================================================================================");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||                 ___  ____________   __________  __________  _____                  ||");
	System.out.println("                                ||                / __\\/_    _/   _/  /  __/_  _/\\/   /  __/ \\/   / \\                 ||");
	System.out.println("                                ||               /    / /  /   \\ \\   /  /__ / //     /  _// /\\/  / __\\                ||");
	System.out.println("                                ||              /_/\\_\\ /__/ /____/   \\____/___/_/\\__/____/_/  /_/_/  \\\\               ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||  Date :"+x+"                                          Location :"+y+"        ||");
	System.out.println("                                ||------------------------------------------------------------------------------------||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||       Name         :"+u+"                                                         ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||       Phone Number :"+q+"                                                      ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||       Tickets      :"+r+"                                                              ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||       Type         :"+i+"                                                          ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||       Time         :"+w+"                                                              ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||       Hall         :"+z+"                                                              ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||       Tax          :"+90*0.8*r+"                                                          ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ||                                                            Total :"+(90*0.8*r+90*r)+"            ||");
	System.out.println("                                ||                                                                                    ||");
	System.out.println("                                ========================================================================================");

	}
}
